url: 'http://fedired.local'

setupPassword: example_password_please_change_this_or_you_will_get_hacked

port: 61812

db:
  host: 127.0.0.1
  port: 54312
  db: test-fedired
  user: postgres
  pass: ''
redis:
  host: 127.0.0.1
  port: 56312
id: aidx